const fs = require('node:fs');
const file = 'server.js';
let s = fs.readFileSync(file, 'utf8');

const oldRun = "function run(cmd,args){return new Promise((resolve,reject)=>{const child=spawn(cmd,args,{stdio:['ignore','ignore','pipe']});let err='';child.stderr.on('data',x=>err+=x);child.on('error',reject);child.on('close',code=>code===0?resolve():reject(new Error(`${cmd} gagal (${code}): ${err.slice(-1000)}`)))})}";
const newRun = "function run(cmd,args,{okCodes=[0]}={}){return new Promise((resolve,reject)=>{const child=spawn(cmd,args,{stdio:['ignore','ignore','pipe']});let err='';child.stderr.on('data',x=>err+=x);child.on('error',reject);child.on('close',code=>okCodes.includes(code)?resolve({code,stderr:err}):reject(new Error(`${cmd} gagal (${code}): ${err.slice(-1000)}`)))})}";
if (!s.includes(oldRun)) throw new Error('run() target not found');
s = s.replace(oldRun, newRun);

const oldProcess = "async function processBook(bookId,sourcePath){const optimized=p('books',`${bookId}.optimized.pdf`);const cover=p('covers',`${bookId}.jpg`);const thumb=p('thumbnails',`${bookId}.jpg`);try{await q('UPDATE books SET status=$2,processing_error=NULL WHERE id=$1',[bookId,'processing']);await run('qpdf',['--check',sourcePath]);await run('qpdf',['--linearize',sourcePath,optimized]);await fs.rename(optimized,sourcePath);await run('pdftoppm',['-f','1','-singlefile','-jpeg','-jpegopt','quality=88,progressive=y','-scale-to-x','1600','-scale-to-y','-1',sourcePath,cover.replace(/\\.jpg$/,'')]);await run('pdftoppm',['-f','1','-singlefile','-jpeg','-jpegopt','quality=72','-scale-to-x','480','-scale-to-y','-1',sourcePath,thumb.replace(/\\.jpg$/,'')]);await q('UPDATE books SET status=$2,cover_path=$3,thumbnail_path=$4,processing_error=NULL WHERE id=$1',[bookId,'ready',cover,thumb])}catch(error){await fs.rm(optimized,{force:true}).catch(()=>{});await q('UPDATE books SET status=$2,processing_error=$3 WHERE id=$1',[bookId,'error',error.message.slice(0,2000)]);app.log.error({err:error,bookId},'book processing failed')}}";
const newProcess = "async function processBook(bookId,sourcePath){const optimized=p('books',`${bookId}.optimized.pdf`);const cover=p('covers',`${bookId}.jpg`);const thumb=p('thumbnails',`${bookId}.jpg`);const renderAssets=async filePath=>{await run('pdftoppm',['-f','1','-singlefile','-jpeg','-jpegopt','quality=88,progressive=y','-scale-to-x','1600','-scale-to-y','-1',filePath,cover.replace(/\\.jpg$/,'')]);await run('pdftoppm',['-f','1','-singlefile','-jpeg','-jpegopt','quality=72','-scale-to-x','480','-scale-to-y','-1',filePath,thumb.replace(/\\.jpg$/,'')])};try{await q('UPDATE books SET status=$2,processing_error=NULL WHERE id=$1',[bookId,'processing']);const check=await run('qpdf',['--check',sourcePath],{okCodes:[0,3]}).catch(error=>{app.log.warn({err:error,bookId},'qpdf check failed; continuing to renderer fallback');return null});if(check?.code===3)app.log.warn({bookId,warning:check.stderr.slice(-1000)},'qpdf reported warnings; continuing');let optimizedReady=false;try{const linearized=await run('qpdf',['--linearize',sourcePath,optimized],{okCodes:[0,3]});optimizedReady=linearized.code===0||await fs.stat(optimized).then(info=>info.size>0).catch(()=>false);if(linearized.code===3)app.log.warn({bookId,warning:linearized.stderr.slice(-1000)},'qpdf linearize completed with warnings')}catch(error){app.log.warn({err:error,bookId},'qpdf linearize failed; using original PDF');await fs.rm(optimized,{force:true}).catch(()=>{})}let usingOptimized=false;if(optimizedReady){try{await renderAssets(optimized);usingOptimized=true}catch(error){app.log.warn({err:error,bookId},'optimized PDF could not render; falling back to original PDF');await fs.rm(optimized,{force:true}).catch(()=>{});await renderAssets(sourcePath)}}else await renderAssets(sourcePath);if(usingOptimized){await fs.rm(sourcePath,{force:true});await fs.rename(optimized,sourcePath)}await q('UPDATE books SET status=$2,cover_path=$3,thumbnail_path=$4,processing_error=NULL WHERE id=$1',[bookId,'ready',cover,thumb])}catch(error){await fs.rm(optimized,{force:true}).catch(()=>{});await q('UPDATE books SET status=$2,processing_error=$3 WHERE id=$1',[bookId,'error',error.message.slice(0,2000)]);app.log.error({err:error,bookId},'book processing failed')}}";
if (!s.includes(oldProcess)) throw new Error('processBook() target not found');
s = s.replace(oldProcess, newProcess);
fs.writeFileSync(file, s);
console.log('Applied resilient PDF processing fallback');
